name: Trigger benchmarks
on:
  push:
    branches:
      - main
  pull_request:
    types: [synchronize]

jobs:
  trigger-benchmark:
    name: Trigger Benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Trigger benchmarks (PR)
        id: setup_pr
        if: contains(github.event.pull_request.labels.*.name, 'benchmark PR')
        env:
          AUTHOR: ${{ github.event.pull_request.assignee.login }}
          BRANCH: ${{ github.head_ref }}
          PIPE_TRIGGER_TOKEN: ${{ secrets.BENCH_PIPE_TRIGGER }}
          SHA: ${{ github.event.pull_request.head.sha }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          SHORT_SHA=$(git rev-parse --short ${{ github.event.pull_request.head.sha }})
          curl -s -X POST \
            --fail-with-body \
            -F "token=$PIPE_TRIGGER_TOKEN" \
            -F "ref=main" \
            -F "variables[SHA]=$SHA" \
            -F "variables[SHORT_SHA]=${SHORT_SHA}" \
            -F "variables[BRANCH]=$BRANCH" \
            -F "variables[PR]=$PR_NUMBER" \
            -F "variables[AUTHOR]=${AUTHOR:heat-team}" \
            https://codebase.helmholtz.cloud/api/v4/projects/7930/trigger/pipeline
      - name: Trigger benchmarks (Push main)
        id: setup_push
        if: ${{ github.event_name == 'push' }}
        env:
          AUTHOR: ${{ github.event.pull_request.assignee.login }}
          PIPE_TRIGGER_TOKEN: ${{ secrets.BENCH_PIPE_TRIGGER }}
          SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          SHORT_SHA=$(git rev-parse --short $GITHUB_SHA)
          curl -s -X POST \
            --fail-with-body \
            -F "token=$PIPE_TRIGGER_TOKEN" \
            -F "ref=main" \
            -F "variables[SHA]=$SHA" \
            -F "variables[SHORT_SHA]=${SHORT_SHA}" \
            -F "variables[BRANCH]=main" \
            -F "variables[AUTHOR]=$AUTHOR" \
            https://codebase.helmholtz.cloud/api/v4/projects/7930/trigger/pipeline
      - name: Create status
        if: ${{ steps.setup_pr.outcome == 'success' || steps.setup_push.outcome == 'success'}}
        env:
          REPO: ${{ github.repository }}
          SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$REPO/statuses/$SHA \
            -d '{ "state":"pending", "target_url":"https://codebase.helmholtz.cloud/helmholtz-analytics/cb/-/pipelines", "description":"Waiting for benchmarks to execute.", "context":"cb/report" }'
