name: Trigger benchmarks
on:
  push:
    branches:
      - main
  pull_request:
    types: [synchronize]

jobs:
  trigger-benchmark:
    name: Trigger Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: LouisBrunner/checks-action@v1.6.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: report_benchmarks
          status: in_progress
          details_url: https://codebase.helmholtz.cloud/helmholtz-analytics/cb/-/pipelines
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get short sha
        id: get_short_sha
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "short_sha=$calculatedSha" >> $GITHUB_OUTPUT
      - name: Trigger benchmarks (PR)
        id: setup_pr
        if: contains(github.event.pull_request.labels.*.name, 'benchmark PR')
        run: |
          curl -s -X POST \
            --fail \
            -F token=${{ secrets.BENCH_PIPE_TRIGGER }} \
            -F "ref=main" \
            -F "variables[SHA]=$GITHUB_SHA" \
            -F "variables[SHORT_SHA]=${{ steps.get_short_sha.outputs.short_sha }}" \
            -F "variables[BRANCH]=${{ github.head_ref }}" \
            -F "variables[PR]=${{ github.event.pull_request.number }}" \
            -F "variables[AUTHOR]=${{ github.event.pull_request.assignee.login }}" \
            https://codebase.helmholtz.cloud/api/v4/projects/7930/trigger/pipeline -o /dev/null
      - name: Trigger benchmarks (Push main)
        id: setup_push
        if: ${{ github.event_name == 'push' }}
        run: |
          curl -s -X POST \
            --fail \
            -F "token=${{ secrets.BENCH_PIPE_TRIGGER }}" \
            -F "ref=main" \
            -F "variables[SHA]=$GITHUB_SHA" \
            -F "variables[SHORT_SHA]=${{ steps.get_short_sha.outputs.short_sha }}" \
            -F "variables[AUTHOR]=${{ github.event.head_commit.committer.username }}" \
            https://codebase.helmholtz.cloud/api/v4/projects/7930/trigger/pipeline -o /dev/null
      - name: Create pending check
        uses: LouisBrunner/checks-action@v1.6.1
        if: steps.setup_pr.outcome == 'failure' || steps.setup_push.outcome == 'failure'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: report_benchmarks
          status: completed
          conclusion: failure
          details_url: https://codebase.helmholtz.cloud/helmholtz-analytics/cb/-/pipelines
