name: Trigger benchmarks
on:
  push:
    branches:
      - main
  pull_request:
    types: [synchronize]

jobs:
  trigger-benchmark:
    name: Trigger Benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get short sha
        id: get_short_sha
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "short_sha=$calculatedSha" >> $GITHUB_OUTPUT
      - name: Trigger benchmarks (PR)
        id: setup_pr
        if: contains(github.event.pull_request.labels.*.name, 'benchmark PR')
        run: |
          curl -s -X POST \
            --fail \
            -F token=${{ secrets.BENCH_PIPE_TRIGGER }} \
            -F "ref=main" \
            -F "variables[SHA]=$GITHUB_SHA" \
            -F "variables[SHORT_SHA]=${{ steps.get_short_sha.outputs.short_sha }}" \
            -F "variables[BRANCH]=${{ github.head_ref }}" \
            -F "variables[PR]=${{ github.event.pull_request.number }}" \
            -F "variables[AUTHOR]=${{ github.event.pull_request.assignee.login }}" \
            https://codebase.helmholtz.cloud/api/v4/projects/7930/trigger/pipeline -o /dev/null
      - name: Create status
        run: |
          gh api --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/$REPO/statuses/$GITHUB_SHA \
            -f state='pending' \
            -f target_url='https://codebase.helmholtz.cloud/helmholtz-analytics/cb/-/pipelines' \
            -f description='Waiting for benchmark results.' \
            -f context='continuous-benchmarking/report'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.repository }}
