name: Create branch on assignment

on:
  # The issues event below is only needed for the default (auto) mode,
  # you can remove it otherwise
  issues:
    types: [ assigned ]

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          egress-policy: audit

      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@caafb70285b1951e15476b11f7053f8b15f7ef9d # main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
